context:
  version: "5.10.2"

package:
  name: tape
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tape/-/tape-${{ version }}.tgz
  sha256: 9f81429a3bf7ba559190f8bef82e369baafe8e989cb0fc3a2bd9356cb68a087c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tape --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: tap-producing test harness for node and browsers
  homepage: https://github.com/tape-testing/tape
  repository: https://github.com/tape-testing/tape

extra:
  recipe-maintainers:
    - danielnachun
