context:
  version: "5.9.0"

package:
  name: tape
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tape/-/tape-${{ version }}.tgz
  sha256: ffbbd1d254d54a829a69b709a83f3a6061f455044fce2a1ee22bc8f2f5918f28

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tape --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: tap-producing test harness for node and browsers
  homepage: https://github.com/tape-testing/tape
  repository: https://github.com/tape-testing/tape

extra:
  recipe-maintainers:
    - danielnachun
